metadata:
  name: miservicio
  namespace: default
  labels:
    container: mideployment
    provider: fabric8
    project: mideployment
    group: com.tibco.bw
kind: Service
spec:
  selector:
    container: mideployment
    provider: fabric8
    project: mideployment
    group: com.tibco.bw
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8890
